apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: otel
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{app:[collector]}"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/sre-project-poc/mainapplication/mainapp:v2
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "http://localhost:4317"
      - image: us-east4-docker.pkg.dev/sre-project-poc/otel/otel
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133