# [START cloudrun_mc_custom_metrics_collector]
FROM otel/opentelemetry-collector-contrib:0.101.0

COPY collector-config.yaml /etc/otelcol-contrib/config.yaml
# [END cloudrun_mc_custom_metrics_collector]
