name: TerraformCloudRun

on:
  workflow_run:
        workflows: ["BuildandPushtoArtifactRegistry"]
        types:
          - completed
  push:
    branches: [ "main" ]
    paths:
      - cloud_run_terraform/**
      - module/run/**
      - .github/workflows/cloudrunterraform.yaml
  pull_request:
    branches: [ "main" ]
    paths:
      - cloud_run_terraform/**
      - module/run/**
      - .github/workflows/cloudrunterraform.yaml
  # For running Github actions manually from UI
  workflow_dispatch:

jobs:
  terraform:
    name: 'terraform-cloud-run'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: cloud_run_terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get run ID of "BuildandPushtoArtifactRegistry" workflow
      run: |
        WF_NAME="Build and Push to Artifact Registry"
        RUN_ID=`gh run list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
        echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
        echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}

    - name: Download artifact from "BuildandPushtoArtifactRegistry" workflow
      uses: actions/download-artifact@v4
      with:
        name: sha-file
        github-token: ${{ secrets.GH_PAT }}
        run-id: ${{ steps.get-run-id.outputs.run-id }}

    - name: Read SHA from file
      id: get-sha
      run: |
        SHA=$(cat sha.txt)
        echo "SHA=$SHA" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Validate
      run: terraform validate
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Plan
      run: terraform plan -var="ingress_image=us-central1-docker.pkg.dev/sre-project-poc/otel-run/mainapp:${{ env.SHA }}" -var="otel_sidecar_image=us-central1-docker.pkg.dev/sre-project-poc/otel-run/otelsidecar:${{ env.SHA }}" -var-file=dev.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Apply
      run: terraform apply -var="ingress_image=us-central1-docker.pkg.dev/sre-project-poc/otel-run/mainapp:${{ env.SHA }}" -var="otel_sidecar_image=us-central1-docker.pkg.dev/sre-project-poc/otel-run/otelsidecar:${{ env.SHA }}" -var-file=dev.tfvars -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}