name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
    paths:
      - app_code/**
      - collector/**
      - .github/workflows/pushtoartifact.yaml
    
  pull_request:
    branches: ["main"]
    paths:
      - app_code/**
      - collector/**
      - .github/workflows/pushtoartifact.yaml
  workflow_dispatch:

env:
  PROJECT_ID: sre-project-poc
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/sre-project-poc/otel-run

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image mainapp
        run: docker build -t ${{ env.GAR_LOCATION }}/mainapp:${{ github.sha }} .
        working-directory: app_code

      - name: Push image mainapp
        run: docker push ${{ env.GAR_LOCATION }}/mainapp:${{ github.sha }}

      - name: Build image sidecar
        run: docker build -t ${{ env.GAR_LOCATION }}/otelsidecar:${{ github.sha }} .
        working-directory: collector

      - name: Push image sidecar
        run: docker push ${{ env.GAR_LOCATION }}/otelsidecar:${{ github.sha }}

      - name: Save SHA to file
        run: echo "${{ github.sha }}" > sha.txt

      - name: Upload SHA file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pushtoartifact-sha
          path: sha.txt