name: Run Composer DAG Task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
        - dev
        - cuat
        - prod
      composer_env:
        description: 'Composer Environment Name'
        required: true
        type: string
      dag_id:
        description: 'DAG ID'
        required: true
        type: string

jobs:
  process-inputs:
    runs-on: ubuntu-latest
    outputs:
      task_id: ${{ steps.get-task-id.outputs.task_id }}
      needs_task: ${{ steps.check-env.outputs.needs_task }}
    steps:
      - id: check-env
        run: |
          if [[ "${{ github.event.inputs.environment }}" =~ ^(cuat|prod)$ ]]; then
            echo "needs_task=true" >> $GITHUB_OUTPUT
          else
            echo "needs_task=false" >> $GITHUB_OUTPUT
          fi

      - id: get-task-id
        if: steps.check-env.outputs.needs_task == 'true'
        run: |
          echo "Please enter Task ID:"
          read TASK_ID
          echo "task_id=$TASK_ID" >> $GITHUB_OUTPUT

  run-composer-task:
    needs: process-inputs
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Run Specific Task (CUAT/PROD)
      if: github.event.inputs.environment == 'cuat' || github.event.inputs.environment == 'prod'
      run: |
        if [ -z "${{ needs.process-inputs.outputs.task_id }}" ]; then
          echo "Error: Task ID is required for CUAT/PROD environments"
          exit 1
        fi
        
        echo "Running specific task in ${{ github.event.inputs.environment }}"
        gcloud composer environments run ${{ github.event.inputs.composer_env }} \
          --location ${{ secrets.GCP_REGION }} \
          test -- \
          ${{ github.event.inputs.dag_id }} \
          ${{ needs.process-inputs.outputs.task_id }}

    - name: Run Full DAG (DEV)
      if: github.event.inputs.environment == 'dev'
      run: |
        echo "Running full DAG in DEV environment"
        gcloud composer environments run ${{ github.event.inputs.composer_env }} \
          --location ${{ secrets.GCP_REGION }} \
          trigger_dag -- \
          ${{ github.event.inputs.dag_id }} \
          --execution_date=${{ github.event.inputs.execution_date }}

    - name: Check Execution Status
      if: always()
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          echo "Execution completed successfully"
        else
          echo "Execution failed"
          exit 1
        fi
